FROM nginx

COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx/nginx.conf /etc/nginx/sites-available/blog.conf
COPY docker/nginx/nginx.conf /etc/nginx/sites-enabled/blog.conf